#------------------------------------------------------------
# Values for this workshop.
#------------------------------------------------------------

# Which carpentry is this ("swc", "dc", "lc", or "cp")?
carpentry: "lc"

# Overall title for the Workshop.
title: "UC Library Carpentry Workshop"

#------------------------------------------------------------
# Generic settings (should not need to change).
#------------------------------------------------------------

kind: "workshop"

# Magic to make URLs resolve both locally and on GitHub.
repository: "jt14den/2026-05-11-uc-lc"

# Email address
email: "tdennis@library.ucla.edu"

# Start time in minutes (540 to show a start at 09:00 am).
start_time: 540

# Turn on built-in syntax highlighting.
highlighter: rouge

# Turn on the custom schedule
# To use this, we need to set the layout to use custom-schedule.html or similar
# But the template's index.md usually handles this.
